/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author juan2
 */
public class Club extends javax.swing.JFrame {

    /**
     * Creates new form Club
     */
    public Club() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoGerente = new javax.swing.JPanel();
        jbt_volverInfoGerente = new javax.swing.JButton();
        jlb_tituloInfoGerente = new javax.swing.JLabel();
        jlb_infoGerenteNombre = new javax.swing.JLabel();
        jlb_infoGerenteApellido = new javax.swing.JLabel();
        jlb_infoGerenteTelefono = new javax.swing.JLabel();
        jlb_infoGerenteDNI = new javax.swing.JLabel();
        jlb_infoGerenteDatosNombre = new javax.swing.JLabel();
        jlb_infoGerenteDatosApellido = new javax.swing.JLabel();
        jlb_infoGerenteDatosTelefono = new javax.swing.JLabel();
        jlb_infoGerenteDatosDNI = new javax.swing.JLabel();
        jlb_infoGerenteNomina = new javax.swing.JLabel();
        jlb_infoGerenteIRPF = new javax.swing.JLabel();
        jbt_infoGerenteNomina = new javax.swing.JButton();
        jbt_infoGerenteIRPF = new javax.swing.JButton();
        InfoEntrenador = new javax.swing.JPanel();
        jlb_clubesTrabaja = new javax.swing.JLabel();
        jbt_volverInfoEntrenador = new javax.swing.JButton();
        jlb_tituloInfoEntrenador = new javax.swing.JLabel();
        jlb_infoEntrenadorNombre = new javax.swing.JLabel();
        jlb_infoEntrenadorApellido = new javax.swing.JLabel();
        jlb_infoEntrenadorTelefono = new javax.swing.JLabel();
        jlb_infoEntrenadorDNI = new javax.swing.JLabel();
        jlb_infoEntrenadorDatosNombre = new javax.swing.JLabel();
        jlb_infoEntrenadorDatosApellido = new javax.swing.JLabel();
        jlb_infoEntrenadorDatosTelefono = new javax.swing.JLabel();
        jlb_infoEntrenadorDatosDNI = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlt_clubesTrabaja = new javax.swing.JList<>();
        ReservarEntrenamiento = new javax.swing.JPanel();
        jlb_tituloReservarEntrenamiento = new javax.swing.JLabel();
        jlb_disponibilidad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlt_listaDisponibilidad = new javax.swing.JList<>();
        jbt_reservar = new javax.swing.JButton();
        jbt_cancelarEntrenamiento = new javax.swing.JButton();
        jlb_tituloNombreClub = new javax.swing.JLabel();
        jbt_volver = new javax.swing.JButton();
        jbt_reservaEntrenamiento = new javax.swing.JButton();
        jlb_entrenador = new javax.swing.JLabel();
        jlb_gerente = new javax.swing.JLabel();
        jlb_federacion = new javax.swing.JLabel();
        jlb_nombreGerente = new javax.swing.JLabel();
        jlb_nombreEntrenador = new javax.swing.JLabel();
        jlb_federacionPerteneciente = new javax.swing.JLabel();
        jbt_infoGerente = new javax.swing.JButton();
        jbt_infoEntrenador = new javax.swing.JButton();

        jbt_volverInfoGerente.setText("volver");
        jbt_volverInfoGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_volverInfoGerenteActionPerformed(evt);
            }
        });

        jlb_tituloInfoGerente.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloInfoGerente.setText("Informacion del Gerente");

        jlb_infoGerenteNombre.setText("nombre:");

        jlb_infoGerenteApellido.setText("apellido:");

        jlb_infoGerenteTelefono.setText("telefono:");

        jlb_infoGerenteDNI.setText("DNI/NIE:");

        jlb_infoGerenteDatosNombre.setText("nombre del gerente");

        jlb_infoGerenteDatosApellido.setText("apellido del gerente");

        jlb_infoGerenteDatosTelefono.setText("telefono del gerente");

        jlb_infoGerenteDatosDNI.setText("DNI del gerente");

        jlb_infoGerenteNomina.setText("nomina:");

        jlb_infoGerenteIRPF.setText("IRPF:");

        jbt_infoGerenteNomina.setText("documento nomina");

        jbt_infoGerenteIRPF.setText("documento IRPF");

        javax.swing.GroupLayout InfoGerenteLayout = new javax.swing.GroupLayout(InfoGerente);
        InfoGerente.setLayout(InfoGerenteLayout);
        InfoGerenteLayout.setHorizontalGroup(
            InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoGerenteLayout.createSequentialGroup()
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoGerenteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbt_volverInfoGerente))
                    .addGroup(InfoGerenteLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoGerenteLayout.createSequentialGroup()
                                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_infoGerenteNombre)
                                    .addComponent(jlb_infoGerenteApellido)
                                    .addComponent(jlb_infoGerenteTelefono)
                                    .addComponent(jlb_infoGerenteDNI))
                                .addGap(65, 65, 65)
                                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_infoGerenteDatosNombre)
                                    .addComponent(jlb_infoGerenteDatosApellido)
                                    .addComponent(jlb_infoGerenteDatosDNI)
                                    .addComponent(jlb_infoGerenteDatosTelefono)))
                            .addGroup(InfoGerenteLayout.createSequentialGroup()
                                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_infoGerenteNomina)
                                    .addComponent(jlb_infoGerenteIRPF))
                                .addGap(65, 65, 65)
                                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbt_infoGerenteNomina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbt_infoGerenteIRPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jlb_tituloInfoGerente))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        InfoGerenteLayout.setVerticalGroup(
            InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoGerenteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlb_tituloInfoGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoGerenteNombre)
                    .addComponent(jlb_infoGerenteDatosNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoGerenteApellido)
                    .addComponent(jlb_infoGerenteDatosApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoGerenteTelefono)
                    .addComponent(jlb_infoGerenteDatosTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoGerenteDNI)
                    .addComponent(jlb_infoGerenteDatosDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoGerenteNomina)
                    .addComponent(jbt_infoGerenteNomina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoGerenteIRPF)
                    .addComponent(jbt_infoGerenteIRPF))
                .addGap(37, 37, 37)
                .addComponent(jbt_volverInfoGerente)
                .addContainerGap())
        );

        jlb_clubesTrabaja.setText("Clubes en los que trabaja:");

        jbt_volverInfoEntrenador.setText("volver");
        jbt_volverInfoEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_volverInfoEntrenadorActionPerformed(evt);
            }
        });

        jlb_tituloInfoEntrenador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloInfoEntrenador.setText("Informacion del Entrenador");

        jlb_infoEntrenadorNombre.setText("nombre:");

        jlb_infoEntrenadorApellido.setText("apellido:");

        jlb_infoEntrenadorTelefono.setText("telefono:");

        jlb_infoEntrenadorDNI.setText("DNI/NIE:");

        jlb_infoEntrenadorDatosNombre.setText("nombre del entrenador");

        jlb_infoEntrenadorDatosApellido.setText("apellido del entrenador");

        jlb_infoEntrenadorDatosTelefono.setText("telefono del entrenador");

        jlb_infoEntrenadorDatosDNI.setText("DNI del entrenador");

        jlt_clubesTrabaja.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlt_clubesTrabaja);

        javax.swing.GroupLayout InfoEntrenadorLayout = new javax.swing.GroupLayout(InfoEntrenador);
        InfoEntrenador.setLayout(InfoEntrenadorLayout);
        InfoEntrenadorLayout.setHorizontalGroup(
            InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEntrenadorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlb_tituloInfoEntrenador)
                    .addGroup(InfoEntrenadorLayout.createSequentialGroup()
                        .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoEntrenadorLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_infoEntrenadorNombre)
                                    .addComponent(jlb_clubesTrabaja)
                                    .addComponent(jlb_infoEntrenadorApellido)
                                    .addComponent(jlb_infoEntrenadorTelefono)
                                    .addComponent(jlb_infoEntrenadorDNI)))
                            .addComponent(jbt_volverInfoEntrenador))
                        .addGap(20, 20, 20)
                        .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_infoEntrenadorDatosNombre)
                            .addComponent(jlb_infoEntrenadorDatosApellido)
                            .addComponent(jlb_infoEntrenadorDatosDNI)
                            .addComponent(jlb_infoEntrenadorDatosTelefono))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoEntrenadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        InfoEntrenadorLayout.setVerticalGroup(
            InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoEntrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_tituloInfoEntrenador)
                .addGap(17, 17, 17)
                .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoEntrenadorNombre)
                    .addComponent(jlb_infoEntrenadorDatosNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoEntrenadorApellido)
                    .addComponent(jlb_infoEntrenadorDatosApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoEntrenadorTelefono)
                    .addComponent(jlb_infoEntrenadorDatosTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_infoEntrenadorDNI)
                    .addComponent(jlb_infoEntrenadorDatosDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb_clubesTrabaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_volverInfoEntrenador)
                .addContainerGap())
        );

        jlb_tituloReservarEntrenamiento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloReservarEntrenamiento.setText("Reservar Entrenamiento");

        jlb_disponibilidad.setText("Disponibilidad:");

        jlt_listaDisponibilidad.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlt_listaDisponibilidad);

        jbt_reservar.setText("reservar");

        jbt_cancelarEntrenamiento.setText("cancelar");

        javax.swing.GroupLayout ReservarEntrenamientoLayout = new javax.swing.GroupLayout(ReservarEntrenamiento);
        ReservarEntrenamiento.setLayout(ReservarEntrenamientoLayout);
        ReservarEntrenamientoLayout.setHorizontalGroup(
            ReservarEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservarEntrenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbt_cancelarEntrenamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_reservar)
                .addContainerGap())
            .addGroup(ReservarEntrenamientoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jlb_disponibilidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservarEntrenamientoLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(ReservarEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservarEntrenamientoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReservarEntrenamientoLayout.createSequentialGroup()
                        .addComponent(jlb_tituloReservarEntrenamiento)
                        .addGap(115, 115, 115))))
        );
        ReservarEntrenamientoLayout.setVerticalGroup(
            ReservarEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservarEntrenamientoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlb_tituloReservarEntrenamiento)
                .addGap(17, 17, 17)
                .addComponent(jlb_disponibilidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(ReservarEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_cancelarEntrenamiento)
                    .addComponent(jbt_reservar))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_tituloNombreClub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloNombreClub.setText("NOMBRE DEL CLUB");

        jbt_volver.setText("volver");

        jbt_reservaEntrenamiento.setText("Reservar Entrenamiento");

        jlb_entrenador.setText("entrenador:");

        jlb_gerente.setText("gerente:");

        jlb_federacion.setText("federacion:");

        jlb_nombreGerente.setText("nombre del gerente");

        jlb_nombreEntrenador.setText("nombre del entrenador");

        jlb_federacionPerteneciente.setText("federacion a la que pertenece");

        jbt_infoGerente.setText("informacion del gerente");
        jbt_infoGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_infoGerenteActionPerformed(evt);
            }
        });

        jbt_infoEntrenador.setText("informacion del entrenador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbt_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_reservaEntrenamiento)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_entrenador)
                                    .addComponent(jlb_gerente)
                                    .addComponent(jlb_federacion, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_nombreGerente)
                                    .addComponent(jlb_nombreEntrenador)
                                    .addComponent(jlb_federacionPerteneciente))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbt_infoEntrenador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbt_infoGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlb_tituloNombreClub)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlb_tituloNombreClub)
                .addGap(27, 27, 27)
                .addComponent(jbt_reservaEntrenamiento)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_gerente)
                    .addComponent(jlb_nombreGerente)
                    .addComponent(jbt_infoGerente))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_entrenador)
                    .addComponent(jlb_nombreEntrenador)
                    .addComponent(jbt_infoEntrenador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_federacionPerteneciente)
                    .addComponent(jlb_federacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jbt_volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_infoGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_infoGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_infoGerenteActionPerformed

    private void jbt_volverInfoGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_volverInfoGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_volverInfoGerenteActionPerformed

    private void jbt_volverInfoEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_volverInfoEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_volverInfoEntrenadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoEntrenador;
    private javax.swing.JPanel InfoGerente;
    private javax.swing.JPanel ReservarEntrenamiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbt_cancelarEntrenamiento;
    private javax.swing.JButton jbt_infoEntrenador;
    private javax.swing.JButton jbt_infoGerente;
    private javax.swing.JButton jbt_infoGerenteIRPF;
    private javax.swing.JButton jbt_infoGerenteNomina;
    private javax.swing.JButton jbt_reservaEntrenamiento;
    private javax.swing.JButton jbt_reservar;
    private javax.swing.JButton jbt_volver;
    private javax.swing.JButton jbt_volverInfoEntrenador;
    private javax.swing.JButton jbt_volverInfoGerente;
    private javax.swing.JLabel jlb_clubesTrabaja;
    private javax.swing.JLabel jlb_disponibilidad;
    private javax.swing.JLabel jlb_entrenador;
    private javax.swing.JLabel jlb_federacion;
    private javax.swing.JLabel jlb_federacionPerteneciente;
    private javax.swing.JLabel jlb_gerente;
    private javax.swing.JLabel jlb_infoEntrenadorApellido;
    private javax.swing.JLabel jlb_infoEntrenadorDNI;
    private javax.swing.JLabel jlb_infoEntrenadorDatosApellido;
    private javax.swing.JLabel jlb_infoEntrenadorDatosDNI;
    private javax.swing.JLabel jlb_infoEntrenadorDatosNombre;
    private javax.swing.JLabel jlb_infoEntrenadorDatosTelefono;
    private javax.swing.JLabel jlb_infoEntrenadorNombre;
    private javax.swing.JLabel jlb_infoEntrenadorTelefono;
    private javax.swing.JLabel jlb_infoGerenteApellido;
    private javax.swing.JLabel jlb_infoGerenteDNI;
    private javax.swing.JLabel jlb_infoGerenteDatosApellido;
    private javax.swing.JLabel jlb_infoGerenteDatosDNI;
    private javax.swing.JLabel jlb_infoGerenteDatosNombre;
    private javax.swing.JLabel jlb_infoGerenteDatosTelefono;
    private javax.swing.JLabel jlb_infoGerenteIRPF;
    private javax.swing.JLabel jlb_infoGerenteNombre;
    private javax.swing.JLabel jlb_infoGerenteNomina;
    private javax.swing.JLabel jlb_infoGerenteTelefono;
    private javax.swing.JLabel jlb_nombreEntrenador;
    private javax.swing.JLabel jlb_nombreGerente;
    private javax.swing.JLabel jlb_tituloInfoEntrenador;
    private javax.swing.JLabel jlb_tituloInfoGerente;
    private javax.swing.JLabel jlb_tituloNombreClub;
    private javax.swing.JLabel jlb_tituloReservarEntrenamiento;
    private javax.swing.JList<String> jlt_clubesTrabaja;
    private javax.swing.JList<String> jlt_listaDisponibilidad;
    // End of variables declaration//GEN-END:variables
}
