/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author aurel
 */
public class Jugador extends javax.swing.JFrame {

    /**
     * Creates new form Jugador
     */
    public Jugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tarjeta_personal = new javax.swing.JPanel();
        jbt_titulo = new javax.swing.JLabel();
        jlb_nombre = new javax.swing.JLabel();
        jlb_apellidos = new javax.swing.JLabel();
        jlb_dni = new javax.swing.JLabel();
        jlb_telefono = new javax.swing.JLabel();
        jlb_categoria = new javax.swing.JLabel();
        jlb_atras = new javax.swing.JButton();
        jlb_elo = new javax.swing.JLabel();
        jl_titulo = new javax.swing.JLabel();
        jbt_club = new javax.swing.JButton();
        jbt_torneo = new javax.swing.JButton();
        jbt_istorial_partidos = new javax.swing.JButton();
        jbt_historial_clubes = new javax.swing.JButton();
        jbt_tarjeta = new javax.swing.JButton();
        jbt_salir = new javax.swing.JButton();
        jbt_responsable = new javax.swing.JButton();

        jbt_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_titulo.setText("TARJETA PERSONAL");

        jlb_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_nombre.setText("Nombre:");

        jlb_apellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_apellidos.setText("Apellidos:");

        jlb_dni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_dni.setText("DNI/NIE:");

        jlb_telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_telefono.setText("Telefono:");

        jlb_categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_categoria.setText("Categotia:");

        jlb_atras.setText("Atrás");

        jlb_elo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_elo.setText("Elo:");

        javax.swing.GroupLayout Tarjeta_personalLayout = new javax.swing.GroupLayout(Tarjeta_personal);
        Tarjeta_personal.setLayout(Tarjeta_personalLayout);
        Tarjeta_personalLayout.setHorizontalGroup(
            Tarjeta_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tarjeta_personalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlb_atras))
            .addGroup(Tarjeta_personalLayout.createSequentialGroup()
                .addGroup(Tarjeta_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tarjeta_personalLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jbt_titulo))
                    .addGroup(Tarjeta_personalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Tarjeta_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlb_elo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_categoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_telefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_dni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_apellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlb_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        Tarjeta_personalLayout.setVerticalGroup(
            Tarjeta_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tarjeta_personalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbt_titulo)
                .addGap(18, 18, 18)
                .addComponent(jlb_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb_apellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb_dni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb_telefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb_categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlb_elo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlb_atras)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jl_titulo.setText("JUGADOR");

        jbt_club.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_club.setText("Inscribirse Club");

        jbt_torneo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_torneo.setText("Unirse Torneo");

        jbt_istorial_partidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_istorial_partidos.setText("Historial Partidos");
        jbt_istorial_partidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_istorial_partidosActionPerformed(evt);
            }
        });

        jbt_historial_clubes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_historial_clubes.setText("Historial Clubes");

        jbt_tarjeta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_tarjeta.setText("Tarjeta Personal");

        jbt_salir.setText("SALIR");

        jbt_responsable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbt_responsable.setText("Responsable");
        jbt_responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_responsableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jl_titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbt_club, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jbt_torneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_responsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_istorial_partidos, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jbt_historial_clubes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_tarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_club)
                    .addComponent(jbt_istorial_partidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_torneo)
                    .addComponent(jbt_historial_clubes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_tarjeta)
                    .addComponent(jbt_responsable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jbt_salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_istorial_partidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_istorial_partidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_istorial_partidosActionPerformed

    private void jbt_responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_responsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_responsableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tarjeta_personal;
    private javax.swing.JButton jbt_club;
    private javax.swing.JButton jbt_historial_clubes;
    private javax.swing.JButton jbt_istorial_partidos;
    private javax.swing.JButton jbt_responsable;
    private javax.swing.JButton jbt_salir;
    private javax.swing.JButton jbt_tarjeta;
    private javax.swing.JLabel jbt_titulo;
    private javax.swing.JButton jbt_torneo;
    private javax.swing.JLabel jl_titulo;
    private javax.swing.JLabel jlb_apellidos;
    private javax.swing.JButton jlb_atras;
    private javax.swing.JLabel jlb_categoria;
    private javax.swing.JLabel jlb_dni;
    private javax.swing.JLabel jlb_elo;
    private javax.swing.JLabel jlb_nombre;
    private javax.swing.JLabel jlb_telefono;
    // End of variables declaration//GEN-END:variables
}
