/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author aange
 */
public class ResponsableInfantil extends javax.swing.JFrame {

    /**
     * Creates new form ResponsableInfantil
     */
    public ResponsableInfantil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResponsable = new javax.swing.JLabel();
        jLabelJuagInfantil = new javax.swing.JLabel();
        jLabelNombreResponsable = new javax.swing.JLabel();
        jLabelApellidoResponsable = new javax.swing.JLabel();
        jLabelNombreJugador = new javax.swing.JLabel();
        jLabelApellidoJugador = new javax.swing.JLabel();
        jTextFieldNombreResponsable = new javax.swing.JTextField();
        jTextFieldApellidoRespinsable = new javax.swing.JTextField();
        jTextFieldNombreJugador = new javax.swing.JTextField();
        jTextFieldApellidoJugador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelResponsable.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabelResponsable.setText("Responsable");

        jLabelJuagInfantil.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelJuagInfantil.setText("Jugador Infantil");

        jLabelNombreResponsable.setText("Nombre");

        jLabelApellidoResponsable.setText("Apellido");

        jLabelNombreJugador.setText("Nombre");

        jLabelApellidoJugador.setText("Apellido");

        jTextFieldNombreResponsable.setText("jTextField1");

        jTextFieldApellidoRespinsable.setText("jTextField2");

        jTextFieldNombreJugador.setText("jTextField3");

        jTextFieldApellidoJugador.setText("jTextField4");
        jTextFieldApellidoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoJugadorActionPerformed(evt);
            }
        });

        jButton1.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jLabelNombreJugador)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(56, 56, 56))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelJuagInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(112, 112, 112)))
                            .addComponent(jLabelApellidoJugador)
                            .addGap(32, 32, 32)
                            .addComponent(jTextFieldApellidoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(221, 221, 221)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombreResponsable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNombreResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))
                        .addComponent(jLabelApellidoResponsable)
                        .addGap(32, 32, 32)
                        .addComponent(jTextFieldApellidoRespinsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResponsable)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreResponsable)
                    .addComponent(jLabelApellidoResponsable)
                    .addComponent(jTextFieldNombreResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidoRespinsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabelJuagInfantil)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreJugador)
                    .addComponent(jLabelApellidoJugador)
                    .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellidoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoJugadorActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelApellidoJugador;
    private javax.swing.JLabel jLabelApellidoResponsable;
    private javax.swing.JLabel jLabelJuagInfantil;
    private javax.swing.JLabel jLabelNombreJugador;
    private javax.swing.JLabel jLabelNombreResponsable;
    private javax.swing.JLabel jLabelResponsable;
    private javax.swing.JTextField jTextFieldApellidoJugador;
    private javax.swing.JTextField jTextFieldApellidoRespinsable;
    private javax.swing.JTextField jTextFieldNombreJugador;
    private javax.swing.JTextField jTextFieldNombreResponsable;
    // End of variables declaration//GEN-END:variables
}
