/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author juan2
 */
public class Torneo extends javax.swing.JFrame {

    /**
     * Creates new form Torneo
     */
    public Torneo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InscribirseTorneo = new javax.swing.JPanel();
        jlb_tituloInscribirseTorneo = new javax.swing.JLabel();
        jlb_torneosDisponibles = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jli_torneos = new javax.swing.JList<>();
        jbt_volverInscribirse = new javax.swing.JButton();
        jbt_inscribirse = new javax.swing.JButton();
        ConfirmacionInscribirseTorneo = new javax.swing.JPanel();
        jlb_texto = new javax.swing.JLabel();
        jbt_ok = new javax.swing.JButton();
        HistorialPartidas = new javax.swing.JPanel();
        jbt_masDetalleHistorial = new javax.swing.JButton();
        jbt_volverHistorial = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jli_historiaPartidos = new javax.swing.JList<>();
        jlb_tituloHistorialPartidos = new javax.swing.JLabel();
        DetallesHistorialPartidas = new javax.swing.JPanel();
        jlb_tituloDetallesPartida = new javax.swing.JLabel();
        jlb_rival = new javax.swing.JLabel();
        jlb_ganador = new javax.swing.JLabel();
        jlb_fecha = new javax.swing.JLabel();
        jlb_tiempo = new javax.swing.JLabel();
        jlb_rivalRespuesta = new javax.swing.JLabel();
        jlb_ganadorlRespuesta = new javax.swing.JLabel();
        jlb_fechaRespuesta = new javax.swing.JLabel();
        jlb_tiempoRespuesta = new javax.swing.JLabel();
        jbt_okDetalles = new javax.swing.JButton();
        ResultadosPartida = new javax.swing.JPanel();
        jlb_tituloResultadoPartido = new javax.swing.JLabel();
        jlb_jugador1 = new javax.swing.JLabel();
        jlb_jugador2 = new javax.swing.JLabel();
        jlb_ganadorResultado = new javax.swing.JLabel();
        jlb_tiempoResultado = new javax.swing.JLabel();
        jlb_torneo = new javax.swing.JLabel();
        jComboBoxTorneo = new javax.swing.JComboBox<>();
        jtf_tiempo = new javax.swing.JTextField();
        jtf_ganador = new javax.swing.JTextField();
        jtf_jugador2 = new javax.swing.JTextField();
        jtf_jugador1 = new javax.swing.JTextField();
        jbt_okResultadoPartido = new javax.swing.JButton();
        jbt_volverResultadoPartido = new javax.swing.JButton();
        jlb_tituloTorneo = new javax.swing.JLabel();
        jbt_inscribirseTorneo = new javax.swing.JButton();
        jbt_historialPartidas = new javax.swing.JButton();
        jbt_resultadosPartida = new javax.swing.JButton();
        jbt_volverTorneo = new javax.swing.JButton();

        jlb_tituloInscribirseTorneo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloInscribirseTorneo.setText("Inscribirse Torneo");

        jlb_torneosDisponibles.setText("Torneos disponibles:");

        jli_torneos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jli_torneos);

        jbt_volverInscribirse.setText("volver");
        jbt_volverInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_volverInscribirseActionPerformed(evt);
            }
        });

        jbt_inscribirse.setText("inscribirse");
        jbt_inscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inscribirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InscribirseTorneoLayout = new javax.swing.GroupLayout(InscribirseTorneo);
        InscribirseTorneo.setLayout(InscribirseTorneoLayout);
        InscribirseTorneoLayout.setHorizontalGroup(
            InscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InscribirseTorneoLayout.createSequentialGroup()
                .addGroup(InscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InscribirseTorneoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbt_volverInscribirse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_inscribirse))
                    .addGroup(InscribirseTorneoLayout.createSequentialGroup()
                        .addGroup(InscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InscribirseTorneoLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jlb_torneosDisponibles))
                            .addGroup(InscribirseTorneoLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InscribirseTorneoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlb_tituloInscribirseTorneo)
                .addGap(121, 121, 121))
        );
        InscribirseTorneoLayout.setVerticalGroup(
            InscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InscribirseTorneoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlb_tituloInscribirseTorneo)
                .addGap(18, 18, 18)
                .addComponent(jlb_torneosDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InscribirseTorneoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_inscribirse)
                    .addComponent(jbt_volverInscribirse))
                .addContainerGap())
        );

        jlb_texto.setText("Has sido inscrito correctamente al torneo");

        jbt_ok.setText("ok");
        jbt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConfirmacionInscribirseTorneoLayout = new javax.swing.GroupLayout(ConfirmacionInscribirseTorneo);
        ConfirmacionInscribirseTorneo.setLayout(ConfirmacionInscribirseTorneoLayout);
        ConfirmacionInscribirseTorneoLayout.setHorizontalGroup(
            ConfirmacionInscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmacionInscribirseTorneoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbt_ok)
                .addContainerGap())
            .addGroup(ConfirmacionInscribirseTorneoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jlb_texto)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        ConfirmacionInscribirseTorneoLayout.setVerticalGroup(
            ConfirmacionInscribirseTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmacionInscribirseTorneoLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jlb_texto)
                .addGap(56, 56, 56)
                .addComponent(jbt_ok)
                .addContainerGap())
        );

        jbt_masDetalleHistorial.setText("mas detalles");

        jbt_volverHistorial.setText("volver");

        jli_historiaPartidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jli_historiaPartidos);

        jlb_tituloHistorialPartidos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloHistorialPartidos.setText("Historial Partidos");

        javax.swing.GroupLayout HistorialPartidasLayout = new javax.swing.GroupLayout(HistorialPartidas);
        HistorialPartidas.setLayout(HistorialPartidasLayout);
        HistorialPartidasLayout.setHorizontalGroup(
            HistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistorialPartidasLayout.createSequentialGroup()
                .addGroup(HistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistorialPartidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbt_volverHistorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_masDetalleHistorial))
                    .addGroup(HistorialPartidasLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(HistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_tituloHistorialPartidos)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HistorialPartidasLayout.setVerticalGroup(
            HistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistorialPartidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_tituloHistorialPartidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(HistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_volverHistorial)
                    .addComponent(jbt_masDetalleHistorial))
                .addContainerGap())
        );

        jlb_tituloDetallesPartida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloDetallesPartida.setText("detalles partida");

        jlb_rival.setText("rival");

        jlb_ganador.setText("ganador");

        jlb_fecha.setText("fecha");

        jlb_tiempo.setText("tiempo");

        jlb_rivalRespuesta.setText("jLabel12");

        jlb_ganadorlRespuesta.setText("jLabel13");

        jlb_fechaRespuesta.setText("jLabel14");

        jlb_tiempoRespuesta.setText("jLabel15");

        jbt_okDetalles.setText("ok");

        javax.swing.GroupLayout DetallesHistorialPartidasLayout = new javax.swing.GroupLayout(DetallesHistorialPartidas);
        DetallesHistorialPartidas.setLayout(DetallesHistorialPartidasLayout);
        DetallesHistorialPartidasLayout.setHorizontalGroup(
            DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesHistorialPartidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbt_okDetalles)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesHistorialPartidasLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jlb_tituloDetallesPartida)
                .addGap(69, 69, 69))
            .addGroup(DetallesHistorialPartidasLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesHistorialPartidasLayout.createSequentialGroup()
                        .addComponent(jlb_ganador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlb_ganadorlRespuesta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesHistorialPartidasLayout.createSequentialGroup()
                        .addComponent(jlb_rival)
                        .addGap(77, 77, 77)
                        .addComponent(jlb_rivalRespuesta))
                    .addGroup(DetallesHistorialPartidasLayout.createSequentialGroup()
                        .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_fecha)
                            .addComponent(jlb_tiempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_fechaRespuesta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlb_tiempoRespuesta, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DetallesHistorialPartidasLayout.setVerticalGroup(
            DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetallesHistorialPartidasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlb_tituloDetallesPartida)
                .addGap(18, 18, 18)
                .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_rival)
                    .addComponent(jlb_rivalRespuesta))
                .addGap(18, 18, 18)
                .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_ganador)
                    .addComponent(jlb_ganadorlRespuesta))
                .addGap(18, 18, 18)
                .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_fecha)
                    .addComponent(jlb_fechaRespuesta))
                .addGap(18, 18, 18)
                .addGroup(DetallesHistorialPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_tiempo)
                    .addComponent(jlb_tiempoRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jbt_okDetalles)
                .addContainerGap())
        );

        jlb_tituloResultadoPartido.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jlb_tituloResultadoPartido.setText("RESULTADO PARTIDO");

        jlb_jugador1.setText("Jugador 1");

        jlb_jugador2.setText("Juagador 2");

        jlb_ganadorResultado.setText("Ganador");

        jlb_tiempoResultado.setText("Tiempo");

        jlb_torneo.setText("Torneo");

        jComboBoxTorneo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTorneoActionPerformed(evt);
            }
        });

        jtf_tiempo.setText("DD/MM/YY");
        jtf_tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_tiempoActionPerformed(evt);
            }
        });

        jtf_ganador.setText("Introduce Nombre y Apellido");

        jtf_jugador2.setText("Introduce Nombre y Apellido");

        jtf_jugador1.setText("Introduce Nombre y Apellido");
        jtf_jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_jugador1ActionPerformed(evt);
            }
        });

        jbt_okResultadoPartido.setText("ok");

        jbt_volverResultadoPartido.setText("volver");

        javax.swing.GroupLayout ResultadosPartidaLayout = new javax.swing.GroupLayout(ResultadosPartida);
        ResultadosPartida.setLayout(ResultadosPartidaLayout);
        ResultadosPartidaLayout.setHorizontalGroup(
            ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadosPartidaLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ResultadosPartidaLayout.createSequentialGroup()
                        .addComponent(jlb_jugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultadosPartidaLayout.createSequentialGroup()
                        .addComponent(jlb_jugador1)
                        .addGap(84, 84, 84)
                        .addComponent(jtf_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultadosPartidaLayout.createSequentialGroup()
                        .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_ganadorResultado)
                            .addComponent(jlb_tiempoResultado)
                            .addComponent(jlb_torneo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultadosPartidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlb_tituloResultadoPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultadosPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbt_volverResultadoPartido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_okResultadoPartido)
                .addContainerGap())
        );
        ResultadosPartidaLayout.setVerticalGroup(
            ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultadosPartidaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlb_tituloResultadoPartido)
                .addGap(32, 32, 32)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_jugador1)
                    .addComponent(jtf_jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_jugador2)
                    .addComponent(jtf_jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_ganadorResultado)
                    .addComponent(jtf_ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_tiempoResultado)
                    .addComponent(jtf_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_torneo)
                    .addComponent(jComboBoxTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ResultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_okResultadoPartido)
                    .addComponent(jbt_volverResultadoPartido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_tituloTorneo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlb_tituloTorneo.setText("Torneo");

        jbt_inscribirseTorneo.setText("Inscribirse Torneo");

        jbt_historialPartidas.setText("Historial partidas");
        jbt_historialPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_historialPartidasActionPerformed(evt);
            }
        });

        jbt_resultadosPartida.setText("Resultados partida");

        jbt_volverTorneo.setText("volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jlb_tituloTorneo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbt_volverTorneo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbt_inscribirseTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_historialPartidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_resultadosPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlb_tituloTorneo)
                .addGap(34, 34, 34)
                .addComponent(jbt_inscribirseTorneo)
                .addGap(18, 18, 18)
                .addComponent(jbt_historialPartidas)
                .addGap(18, 18, 18)
                .addComponent(jbt_resultadosPartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jbt_volverTorneo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_volverInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_volverInscribirseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_volverInscribirseActionPerformed

    private void jbt_inscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inscribirseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_inscribirseActionPerformed

    private void jbt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_okActionPerformed

    private void jbt_historialPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_historialPartidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_historialPartidasActionPerformed

    private void jComboBoxTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTorneoActionPerformed

    private void jtf_jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_jugador1ActionPerformed

    private void jtf_tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tiempoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConfirmacionInscribirseTorneo;
    private javax.swing.JPanel DetallesHistorialPartidas;
    private javax.swing.JPanel HistorialPartidas;
    private javax.swing.JPanel InscribirseTorneo;
    private javax.swing.JPanel ResultadosPartida;
    private javax.swing.JComboBox<String> jComboBoxTorneo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbt_historialPartidas;
    private javax.swing.JButton jbt_inscribirse;
    private javax.swing.JButton jbt_inscribirseTorneo;
    private javax.swing.JButton jbt_masDetalleHistorial;
    private javax.swing.JButton jbt_ok;
    private javax.swing.JButton jbt_okDetalles;
    private javax.swing.JButton jbt_okResultadoPartido;
    private javax.swing.JButton jbt_resultadosPartida;
    private javax.swing.JButton jbt_volverHistorial;
    private javax.swing.JButton jbt_volverInscribirse;
    private javax.swing.JButton jbt_volverResultadoPartido;
    private javax.swing.JButton jbt_volverTorneo;
    private javax.swing.JLabel jlb_fecha;
    private javax.swing.JLabel jlb_fechaRespuesta;
    private javax.swing.JLabel jlb_ganador;
    private javax.swing.JLabel jlb_ganadorResultado;
    private javax.swing.JLabel jlb_ganadorlRespuesta;
    private javax.swing.JLabel jlb_jugador1;
    private javax.swing.JLabel jlb_jugador2;
    private javax.swing.JLabel jlb_rival;
    private javax.swing.JLabel jlb_rivalRespuesta;
    private javax.swing.JLabel jlb_texto;
    private javax.swing.JLabel jlb_tiempo;
    private javax.swing.JLabel jlb_tiempoRespuesta;
    private javax.swing.JLabel jlb_tiempoResultado;
    private javax.swing.JLabel jlb_tituloDetallesPartida;
    private javax.swing.JLabel jlb_tituloHistorialPartidos;
    private javax.swing.JLabel jlb_tituloInscribirseTorneo;
    private javax.swing.JLabel jlb_tituloResultadoPartido;
    private javax.swing.JLabel jlb_tituloTorneo;
    private javax.swing.JLabel jlb_torneo;
    private javax.swing.JLabel jlb_torneosDisponibles;
    private javax.swing.JList<String> jli_historiaPartidos;
    private javax.swing.JList<String> jli_torneos;
    private javax.swing.JTextField jtf_ganador;
    private javax.swing.JTextField jtf_jugador1;
    private javax.swing.JTextField jtf_jugador2;
    private javax.swing.JTextField jtf_tiempo;
    // End of variables declaration//GEN-END:variables
}
